### DISCUSSION TITLE
Critical CSS Update

### DISCUSSION THREAD

**Discussion by therazman** [scambier/obsidian-omnisearch#226] [Ideas]
![Untitled-1](https://user-images.githubusercontent.com/4894372/232834845-a30bb475-d3e7-43ef-9483-5455b8568ab5.png)

We need this CSS line to align the file icon with the title.
```CSS
span.omnisearch-result__title > span {
    display: flex;
}
```

And this line, which hides the folder in which a file is located, would be nice to be added as a togglable feature.
```CSS
.omnisearch-result__folder-path {
    display: none;
}
```
