### ISSUE TITLE
Since 0.2.0, highlighted parts of titles aren't visible

### ISSUE THREAD

**Issue by Sanqui** [scambier/obsidian-omnisearch#17]
Since 0.2.0 changed the yellow highlights to bold, it's no longer possible to tell which part (if any) of the result's title matches the search term, because the entire title is bold.  In my opinion this is a regression and hampers navigation.  Personally, I didn't mind the yellow (would probably re-enable it if there was an option for it) but if you really don't want color, please use some other indicator like underline to show a match in the page title :)

![image](https://user-images.githubusercontent.com/289437/164492201-4a0c1049-74b0-48d1-8645-e20c8ec94f52.png)

**Comment by scambier** [comment]
Yeah actually I forgot to "highlight" the matches in the title 😅

Once it's fixed and published, you can add the following css snippet to restore the yellow highlighting:
```css
.omnisearch-highlight {
    color: var(--text-normal);
    background-color: var(--text-highlight-bg);
}
```

I plan to add a setting for this later.
