### ISSUE TITLE
[BUG] omnisearch-highlight CSS highlight update not effective

### ISSUE THREAD

**Issue by dkzsys** [scambier/obsidian-omnisearch#366]
**Problem description:**

I am trying to update the omnisearch result highlight with yellow background; unfortunately, I'm unable to achieve that using CSS styling for omnisearch-highlight.

**Your environment:**

- Omnisearch version: 1.22.2
- Obsidian version: v.1.5.12
- Operating system: mac OS 14.2.1
- Number of indexed documents in your vault (approx.): ~500
- MInimal Theme: 7.5

**Things I tried:**

I have tried the following 2 CSS Styling. Unfortunately, no change to the highlight.

```
.omnisearch-highlight {
  color: var(--text-normal);
  background-color: var(--text-highlight-bg);
}
```

```
.omnisearch-highlight {
  color: white;
  background-color: yellow;
}
```

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Sample search result**
![image](https://github.com/scambier/obsidian-omnisearch/assets/39715311/604dc5ab-76e2-439c-afdb-12045f21d18d)

**Comment by dkzsys** [comment]
I've tried updating the CSS styling for .omnisearch-result__title and it works.

`.omnisearch-result__title {
  color: var(--text-normal);
  background-color: var(--text-highlight-bg); 
}`

![image](https://github.com/scambier/obsidian-omnisearch/assets/39715311/54702bfd-b29c-4cd4-b2ab-04aad4153d90)

**Comment by scambier** [comment]
I just tried with
```css
.omnisearch-highlight {
  color: white;
  background-color: yellow;
}
```

and it works as expected. Maybe try to add `!important`?

```css
.omnisearch-highlight {
  color: white !important;
  background-color: yellow !important;
}
```
