### ISSUE TITLE
[Feature request] Search results are displayed in a more readable way like this

### ISSUE THREAD

**Issue by jiajiala** [scambier/obsidian-omnisearch#393]
**Is your feature request related to a problem? Please describe.**
The amount of information I get every time I search makes it difficult to find what I want to focus on in the first place
So hopefully the search results will be more readable
Changes like this
![image](https://github.com/user-attachments/assets/8bdf98ee-ca50-41f8-a9bd-3979467eda78)
Put the path to the file after the file, and use a flashback structure
In this way, the file will be seen first, and then the folder it is in will be seen, and then the full path it is in will be noticed, up to the top folder. If the path is too long, the top folder will be omitted instead of the folder it is in

I have tried to use css to achieve this effect, but my ability is limited and I can't find a way to achieve it. I hope you can help me
And I think if more users can use this design, it will definitely help them

Thanks again for making this plugin

**Comment by scambier** [comment]
I'm not sure it's possible to insert the folder between the filename and the number of matches without changing the html.

But this snippet will put the filename and the folder on the same line
```css
.suggestion-item .omnisearch-result {
    width: 100%;
}

div:has(> .omnisearch-result__title-container) {
    width: 100%;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between; /* or flex-start */
}

.omnisearch-result__folder-path {
    margin-left: 1em;
}

div:has(> .omnisearch-result__body) {
    display: flex;
    flex: 1 1 100%;
}

.omnisearch-result__body {
    flex: 1 1 100%;
}
```

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/3b91b1e2-7d2f-4774-9a93-7df3d0f7d6db)
I wonder if I can remove these two ICONS
They mean nothing to me and make the search confusing

**Comment by scambier** [comment]
```css
.omnisearch-result svg {
    display: none;
}
```
