### ISSUE TITLE
Hide Shortcuts

### ISSUE THREAD

**Issue by ParadoxPacer** [scambier/obsidian-omnisearch#404]
I was wondering if there was a way to hide the shortcuts which are displayed when using omnisearch, maybe as a toggleabble setting. although if anyone knows how to get rid of the shortcuts through a css snippet, that would also be helpful.
![image](https://github.com/user-attachments/assets/3085c072-6bb8-4821-a64b-6a6b042df961)

**Comment by scambier** [comment]
```css
.omnisearch-modal .prompt-instructions {
  display: none;
}
```

![image](https://github.com/user-attachments/assets/cf80ba6f-2114-4aca-96f9-018258abf51a)
